version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/home/node/app
    container_name: ts-node-docker
    command: npm run dev